"""
Guardrails / Safety Rules (确定性安全拦截护栏)
-----------------------------------------------
[Design Intent / 设计意图]
This module represents the Security & Guardrail layer of the agentic pipeline. In alignment 
with the Unit 5 guideline of developing secure and production-grade agents, we enforce a 
"Zero-Trust" (零信任) security check. We do not rely on LLM alignment alone. Instead, 
we pass the final LLM output through this deterministic Python rule engine to eliminate 
high-risk trading suggestions (the Gambler's Fallacy / 赌徒谬误).

[Implementation / 实现细节]
- Uses regex pattern matching (`DANGEROUS_PATTERNS`) to identify high-risk trading anti-patterns:
  - "加仓摊平" (averaging down on losses)
  - "扛单" (holding onto losing trades without SL)
  - "锁仓" (hedging to lock paper losses)
  - "马丁格尔" (Martingale sizing multiplier)
- If a pattern is matched, `sanitize_advice` intercepts the entire text block and replaces it 
  with a standardized warning message, preventing any unsafe content from reaching the client interface.

[Behavior / 行为规范]
- Input: Raw text suggestion generated by the LLM.
- Output: The original text if no patterns match, or a standardized secure fallback warning message.
"""

import re

# List of dangerous patterns matching gambling behavioral fallacies
DANGEROUS_PATTERNS = [
    r"加仓.*回本",
    r"摊平成本",
    r"扛单",
    r"加大仓位.*亏损",
    r"all[\s-]?in",
    r"martingale",
    r"马丁格尔",
    r"梭哈",
    r"加倍下注",
]


def contains_dangerous_advice(text: str) -> bool:
    """Scans the text against dangerous trading patterns.

    Args:
        text: The text string to evaluate.

    Returns:
        True if any dangerous pattern matches, otherwise False.
    """
    lowered = text.lower()
    for pattern in DANGEROUS_PATTERNS:
        if re.search(pattern, lowered, re.IGNORECASE):
            return True
    return False


def sanitize_advice(text: str) -> str:
    """Interceptors output from LLM and sanitizes any dangerous advice.

    Args:
        text: Raw generated output text.

    Returns:
        Original text if safe, or a replacement warning if dangerous.
    """
    if contains_dangerous_advice(text):
        return (
            "[安全护栏已拦截原始建议] 检测到该建议可能包含高风险的仓位管理逻辑"
            "（例如加仓摊平、扛单等）。系统不会输出此类建议。"
            "建议改为：复盘止损位设置是否合理、降低单笔风险敞口、"
            "或咨询持牌财务顾问。"
        )
    return text


def validate_position_size_suggestion(suggested_lot: float, account_balance: float) -> dict:
    """Deterministic validation logic to ensure recommended size does not cross safety margins.

    Args:
        suggested_lot: Recommended size (in lots or value).
        account_balance: Capital account balance.

    Returns:
        Dictionary indicating safety assessment status.
    """
    max_allowed = account_balance * 0.02  # Strict 2% single-trade risk constraint
    is_safe = suggested_lot <= max_allowed
    return {
        "is_safe": is_safe,
        "suggested_lot": suggested_lot,
        "max_allowed_lot": round(max_allowed, 2),
        "reason": "OK" if is_safe else "建议仓位超过账户2%风险上限，已被拦截",
    }
