"""
Critic Agent
-----------------------------
[Design Intent]
This agent serves as the Quality Assurance (QA) and Critic node in our multi-agent pipeline 
(inspired by the 'Predict Pro' architecture). It audits the generated suggestions 
from the Advisor Agent to ensure they are quantitative, professional, and contain no safety issues.

[Implementation]
- Built using the Google Agent Development Kit (ADK) `Agent` class.
- Chains after the Advisor Agent in the sequential workflow.
- Acts as a critic: If the advice is too vague, it refines and rewrites it to match strict 
  quantitative standards, quoting exact ratios and percentages from the Analysis Agent.

[Behavioral Standards]
- Input: Text advisory report containing calculations and recommendations.
- Output: Refined, formatted, and strictly quantitative wind-down advisory.
"""

from google.adk import Agent
from google.adk.agents.callback_context import CallbackContext
from google.adk.models import LlmResponse
from trading_risk_coach.guardrails.safety_rules import sanitize_advice


async def safety_guardrail_callback(callback_context: CallbackContext, llm_response: LlmResponse, **kwargs) -> LlmResponse:
    """Apply the deterministic safety filter to the final critic output."""
    if hasattr(llm_response, "text") and llm_response.text is not None:
        llm_response.text = sanitize_advice(llm_response.text)
    elif llm_response.content and llm_response.content.parts:
        for part in llm_response.content.parts:
            if part.text:
                part.text = sanitize_advice(part.text)
    return llm_response

# Define the Critic Agent
critic_agent = Agent(
    name="critic_agent",
    model="gemini-3.1-flash-lite",
    description="Audits and formats final risk reports to ensure compliance and strict quantitative metrics support.",
    after_model_callback=safety_guardrail_callback,
    instruction="""You are a wind control auditor (Critic Agent).

Your tasks:
1. Audit and refine the risk report generated by the previous agent (advisor_agent).
2. Ensure the final report includes:
   - A clear wind-control rating status: [GREEN - SAFE], [YELLOW - WATCH], or [RED - BREAKER], along with justifications.
   - Exact quantitative metrics cited (e.g., "Win Rate: 45.0%", "Profit-to-Loss Ratio: 2.71x"). If the previous suggestions are vague, look them up in the analysis data and make them explicit.
3. Optimize the formatting to present a highly professional, well-structured "Quantitative Risk Audit Report" suitable for institutional traders.
4. Ensure absolute safety: If you detect any implicit hints of averaging down or holding onto losses, delete them immediately and replace them with safety warning templates.

Output format:
---
# 📊 Quantitative Risk Audit Report (XAUUSD Account)

## 🚨 Account Risk Rating: [Fill in Green/Yellow/Red status and justifications here]

## 📈 Core Performance Metrics:
- Win Rate: ...
- Profit-to-Loss Ratio: ...
- Concentration Risk: ...

## 🛡️ Active Risk Mitigation Logs:
- [List executed actions, e.g., stop-loss placement or emergency close response records]

## 💡 Behavioral De-biasing Recommendations:
1. [Recommendation 1 with supporting metrics]
2. [Recommendation 2 with supporting metrics]
"""
)
